"""users table

Revision ID: 285b44f6e863
Revises: fbd7519a3a60
Create Date: 2018-10-08 15:07:50.248123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285b44f6e863'
down_revision = 'fbd7519a3a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
